apply_net_commands:
  builtin: []
apt:
  http_proxy: ''
  https_proxy: ''
  preserve_sources_list: false
  primary:
  - arches:
    - default
    uri: http://jp.archive.ubuntu.com/ubuntu
curthooks_commands:
  builtin:
  - curtin
  - curthooks
extract_commands:
  builtin:
  - curtin
  - extract
hook_commands:
  builtin:
  - curtin
  - hook
install:
  error_tarfile: /var/log/curtin/curtin-error-logs.tar
  log_file: /var/log/curtin/install.log
  save_install_config: /var/log/installer/curtin-install-cfg.yaml
  save_install_log: /var/log/installer/curtin-install.log
  target: /target
  unmount: disabled
late_commands:
  builtin: []
network:
  ethernets:
    enp4s0:
      addresses: []
      dhcp4: true
  version: 2
network_commands:
  builtin:
  - curtin
  - net-meta
  - auto
partitioning_commands:
  builtin:
  - curtin
  - block-meta
  - simple
pollinate:
  user_agent:
    subiquity: 0+git.ffed9d3_620
proxy:
  http_proxy: ''
  https_proxy: ''
reporting:
  subiquity:
    identifier: curtin_event.1798
    type: journald
sources:
  ubuntu00:
    type: tgz
    uri: cp:///media/filesystem
stages:
- early
- partitioning
- network
- extract
- curthooks
- hook
- late
storage:
  config:
  - grub_device: false
    id: disk-0
    model: INTEL SSDPEKKW512G8
    name: ''
    path: /dev/nvme0n1
    preserve: false
    ptable: gpt
    serial: INTEL SSDPEKKW512G8_SERIAL
    type: disk
    wipe: superblock
  - grub_device: true
    id: disk-1
    model: INTEL_SSDSC2CT120A3
    name: ''
    path: /dev/sda
    preserve: false
    ptable: gpt
    serial: INTEL_SSDSC2CT120A3_SERIAL
    type: disk
    wipe: superblock
  - device: disk-0
    flag: ''
    id: part-1
    preserve: false
    size: 1073741824
    type: partition
  - device: disk-0
    flag: ''
    id: part-2
    preserve: false
    size: 511033999360
    type: partition
  - device: disk-1
    flag: boot
    id: part-3
    preserve: false
    size: 536870912
    type: partition
  - device: disk-1
    flag: ''
    id: part-4
    preserve: false
    size: 1073741824
    type: partition
  - devices:
    - part-2
    id: vg-0
    name: ubuntu-vg
    type: lvm_volgroup
  - id: lv-0
    name: ubuntu-lv
    size: 4294967296b
    type: lvm_partition
    volgroup: vg-0
  - fstype: ext4
    id: fs-1
    preserve: false
    type: format
    volume: part-1
  - fstype: ext4
    id: fs-2
    preserve: false
    type: format
    volume: lv-0
  - fstype: fat32
    id: fs-3
    preserve: false
    type: format
    volume: part-3
  - fstype: ext4
    id: fs-4
    preserve: false
    type: format
    volume: part-4
  - device: fs-2
    id: mount-2
    path: /
    type: mount
  - device: fs-4
    id: mount-4
    path: /boot
    type: mount
  - device: fs-3
    id: mount-3
    path: /boot/efi
    type: mount
  version: 1
verbosity: 3
write_files:
  etc_default_keyboard:
    content: '# KEYBOARD CONFIGURATION FILE


      # Consult the keyboard(5) manual page.


      XKBMODEL="pc105"

      XKBLAYOUT="jp"

      XKBVARIANT=""

      XKBOPTIONS=""


      BACKSPACE="guess"

      '
    path: etc/default/keyboard
